{
 "title": "Action runner controller",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } },
   { "name": "runner_name", "query": { "query": "label_values(name)" } },
   { "name": "name", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Process CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Process CPU Seconds"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (server,instance) (go_goroutines{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Open FDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (process_open_fds{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Runners ($runner_name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "horizontalrunnerautoscaler_runners{job=\"$scrape_jobs\", name=\"$runner_name\"}"
    },
    {
     "expr": "horizontalrunnerautoscaler_runners_busy{job=\"$scrape_jobs\", name=\"$runner_name\"}"
    },
    {
     "expr": "horizontalrunnerautoscaler_runners_registered{job=\"$scrape_jobs\", name=\"$runner_name\"}"
    }
   ]
  },
  {
   "title": "REST Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rest_client_requests_total{job=\"$scrape_jobs\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "workqueue_adds_total",
   "type": "timeseries",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "workqueue_adds_total{job=\"$scrape_jobs\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Github Rate Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "github_rate_limit_remaining{job=\"$scrape_jobs\"}",
     "legendFormat": "Github Rate Limit"
    }
   ]
  },
  {
   "title": "Work Duration ($name)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "workqueue_work_duration_seconds_bucket{job=\"$scrape_jobs\", name=\"$name\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queue Duration ($name)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "workqueue_queue_duration_seconds_bucket{job=\"$scrape_jobs\", name=\"$name\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}